export { default as mainHero } from "./main-hero.png"
export { default as academicIcon } from "./academic-icon.png"
export { default as personalIcon } from "./personal-icon.png"
export { default as workIcon } from "./work-icon.png"
export { default as midoriAvatar } from "./midori-avatar.jpg"
export { default as misoBefore } from "./miso-before.png"
export { default as misoAfter } from "./miso-after.png"
export { default as bowlBefore } from "./bowl-before.png"
export { default as bowlAfter } from "./bowl-after.png"

export { default as midoriDrinking } from "./about/midori-drinking.jpg"
export { default as midoriExcel } from "./about/midori-excel.jpg"

export { default as photoshopIcon } from "./tools/photoshop.png"
export { default as premiereProIcon } from "./tools/premiere-pro.png"
export { default as illustratorIcon } from "./tools/illustrator.png"
export { default as indesignIcon } from "./tools/indesign.png"
export { default as frescoIcon } from "./tools/fresco.png"
export { default as davinciResolveIcon } from "./tools/davinci-resolve.png"
export { default as capcutIcon } from "./tools/capcut.png"
export { default as canvaIcon } from "./tools/canva.png"
export { default as amplienceIcon } from "./tools/amplience.png"
